### ISSUE TITLE
Switch to ES vNext build pipeline

### ISSUE THREAD

**Issue by samandmoore** [Betterment/test_track_js_client#6]
It would be highly beneficial to switch to a ES2016/ES6/ESvNext build pipeline. By introducing [Babel](https://babeljs.io/), we will be able to make our mostly OO JS code more readable, maintainable, and approachable.

/cc @chrislopresto

**Comment by chrislopresto** [comment]
+10,000 to this

**Comment by rynonl** [comment]
Does this constitute something of a rewrite?

**Comment by samandmoore** [comment]
@rynonl not necessarily. It can be done in an incremental way.
